"""extract_vitaldb.py — auto-generated by Afferent Intelligence.

Pulls a tidy per-case CSV for this study from the OPEN VitalDB dataset.
Review and adjust before running. Requires:  pip install vitaldb pandas numpy

The open VitalDB subset is downloadable without credentialing via the public API.
Track names below come from the verified inventory.
"""
import numpy as np, pandas as pd

CASE_LIMIT = 100   # raise to None for the full cohort once you have verified the script

CLINICAL_COLS = ['age', 'ane_type', 'asa', 'caseid', 'death_inhosp', 'department', 'emop', 'icu_days', 'optype', 'sex']
LAB_NAMES     = ['cr']
TRACKS        = ['Solar8000/ART_MBP']

# --- 1. clinical information (one row per case) -----------------------------
clin = pd.read_csv("https://api.vitaldb.net/cases")
clin = clin[[c for c in CLINICAL_COLS if c in clin.columns]].copy()

# --- 2. cohort filters (from your scoping parameters) -----------------------
clin = clin[clin['age'] >= 18]
clin = clin[clin['age'] <= 90]
clin = clin[clin['asa'].isin([2, 3])]
clin = clin[clin['ane_type'].astype(str).str.contains('General', case=False, na=False)]
clin["los_days"] = None  # derive from adm/dis if needed: (clin['dis']-clin['adm'])/86400

caseids = clin["caseid"].tolist()
if CASE_LIMIT:
    caseids = caseids[:CASE_LIMIT]
clin = clin[clin["caseid"].isin(caseids)]

# --- 3. perioperative labs (long -> wide summary; e.g. baseline & peak) ------
if LAB_NAMES:
    labs = pd.read_csv("https://api.vitaldb.net/labs")
    labs = labs[labs["name"].isin(LAB_NAMES) & labs["caseid"].isin(caseids)]
    # baseline (closest pre-op) and postoperative peak per case/test:
    labs_pre  = labs[labs["dt"] <= 0].sort_values("dt").groupby(["caseid", "name"]).last()["result"].unstack()
    labs_post = labs[labs["dt"] >  0].groupby(["caseid", "name"])["result"].max().unstack()
    labs_pre.columns  = [f"{c}_baseline" for c in labs_pre.columns]
    labs_post.columns = [f"{c}_postop_peak" for c in labs_post.columns]
    clin = clin.merge(labs_pre, on="caseid", how="left").merge(labs_post, on="caseid", how="left")

# --- 4. intraoperative tracks (summarise each waveform/numeric per case) -----
if TRACKS:
    import vitaldb
    rows = []
    for cid in caseids:
        feat = {"caseid": cid}
        try:
            vf = vitaldb.VitalFile(cid, TRACKS)
            df = vf.to_pandas(TRACKS, 1)        # 1-second resolution over the case
            for t in TRACKS:
                if t in df:
                    s = pd.to_numeric(df[t], errors="coerce")
                    feat[f"{t}_mean"] = np.nanmean(s)
                    feat[f"{t}_min"]  = np.nanmin(s)
                    feat[f"{t}_max"]  = np.nanmax(s)
        except Exception as e:
            print("skip", cid, e)
        rows.append(feat)
    clin = clin.merge(pd.DataFrame(rows), on="caseid", how="left")

# TODO: operationalize the exposure/outcome from your scoping parameters here,
#       e.g. hypotension_minutes = time with Solar8000/ART_MBP_mean < 65.

clin.to_csv("extracted_cohort.csv", index=False)
print("wrote extracted_cohort.csv:", clin.shape)
